CREATE TABLE `ht_user`.`users` (
                                   `id` bigint(20) NOT NULL AUTO_INCREMENT,
                                   `user_name` varchar(32) NOT NULL COMMENT '用户名称, 登陆用户名',
                                   `user_role_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '用户角色',
                                   `password` varchar(32) NOT NULL COMMENT '用户密码, MD5存储',
                                   `users_department_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '用户部门ID',
                                   `user_group_id` bigint(20) NOT NULL DEFAULT '-1' COMMENT '所属分组id',
                                   `status` int(1) NOT NULL DEFAULT '0' COMMENT '账号状态, 1:正常   0:禁用',
                                   `city_id` int(11) NOT NULL DEFAULT '0' COMMENT '所属城市',
                                   `avatar` varchar(128) DEFAULT NULL COMMENT '用户头像',
                                   `last_login_time` datetime DEFAULT NULL COMMENT '最后一次登陆时间, -1表示首次登陆',
                                   `all_trucks` int(4) NOT NULL DEFAULT '0' COMMENT '1代表所有车辆，0代表指定车辆，当为0是user_truck_permission表数据才会生效',
                                   `name` varchar(16) NOT NULL DEFAULT '' COMMENT '用户姓名(中文)',
                                   `mobile` varchar(11) NOT NULL DEFAULT '' COMMENT '手机号',
                                   `on_duty` varchar(16) NOT NULL DEFAULT '' COMMENT '周几值班, 1表示周一,xxxxx, 7表示周日,逗号分割',
                                   `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                   `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                   `create_users_id` bigint(20) DEFAULT NULL,
                                   `update_users_id` bigint(20) DEFAULT NULL,
                                   `wechat_user_name` varchar(32) NOT NULL DEFAULT '' COMMENT '企业微信账号',
                                   `last_login_ip` varchar(32) DEFAULT NULL COMMENT '登录的ip',
                                   `rules` varchar(2000) DEFAULT NULL COMMENT '用户组拥有的规则id， 多个规则","隔开',
                                   `company_id` int(10) DEFAULT '1' COMMENT '公司id',
                                   `region` varchar(100) DEFAULT NULL COMMENT '所在区域',
                                   `region_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '区域id',
                                   `region_group_Id` bigint(20) NOT NULL DEFAULT '0' COMMENT '区域小组id',
                                   `saler_group` int(1) NOT NULL DEFAULT '0' COMMENT '销售分组 0普通 1 拉新 2留存',
                                   `job_number` varchar(10) DEFAULT NULL COMMENT '工单号',
                                   `system_type` int(5) DEFAULT '0' COMMENT '系统状态0正常；1-停单2停单（更新）3停职，4停职更新',
                                   `stop_time` datetime DEFAULT NULL COMMENT '停单/停职时间',
                                   PRIMARY KEY (`id`) USING BTREE,
                                   KEY `idx_name_fatherid_status` (`user_name`,`status`),
                                   KEY `IDX_DID` (`users_department_id`) USING BTREE,
                                   KEY `users_region_id_index` (`region_id`)
) ENGINE=InnoDB AUTO_INCREMENT=998001512510200 DEFAULT CHARSET=utf8mb4 COMMENT='用户表'